# Generated by Django 5.0.2 on 2024-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='author',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='quote',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='tags',
            field=models.CharField(),
        ),
    ]
